# Generated by Django 4.0.4 on 2022-05-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_alter_categories_category_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
