# Generated by Django 4.0.4 on 2022-06-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_products_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='name',
        ),
        migrations.CreateModel(
            name='Sinov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ManyToManyField(to='basic_app.konsultatsiya')),
            ],
        ),
    ]
