# Generated by Django 4.0.4 on 2022-06-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_remove_products_name_sinov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konsultatsiya',
            name='name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Ваше имя'),
        ),
        migrations.AlterField(
            model_name='konsultatsiya',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Ваше номер'),
        ),
    ]
